const scancode = @import("scancode.zig");

/// The SDL virtual key representation.
///
/// Values of this type are used to represent keyboard keys using the current
/// layout of the keyboard. These values include Unicode values representing
/// the unmodified character that would be generated by pressing the key, or an
/// `SDLK_*` constant for those keys that do not generate characters.
///
/// A special exception is the number keys at the top of the keyboard which map
/// by default to SDLK_0...SDLK_9 on AZERTY layouts.
///
/// Keys with the `SDLK_EXTENDED_MASK` bit set do not map to a scancode or
/// Unicode code point.
///
/// Many common keycodes are listed below, but this list is not exhaustive.
///
/// \since This datatype is available since SDL 3.2.0.
///
/// \sa SDL_HINT_KEYCODE_OPTIONS
pub const SDL_Keycode = enum(u32) {
    /// 1 << 29
    extended_mask = 0x20000000,
    /// 1 << 30
    scancode_mask = 0x40000000,
    /// 0
    unknown = 0x00000000,
    /// '\r'
    return_key = 0x0000000d,
    /// '\x1B'
    escape = 0x0000001b,
    /// '\b'
    backspace = 0x00000008,
    /// '\t'
    tab = 0x00000009,
    /// ' '
    space = 0x00000020,
    /// '!'
    exclaim = 0x00000021,
    /// '"'
    dblapostrophe = 0x00000022,
    /// '#'
    hash = 0x00000023,
    /// '$'
    dollar = 0x00000024,
    /// '%'
    percent = 0x00000025,
    /// '&'
    ampersand = 0x00000026,
    /// '\''
    apostrophe = 0x00000027,
    /// '('
    leftparen = 0x00000028,
    /// ')'
    rightparen = 0x00000029,
    /// '*'
    asterisk = 0x0000002a,
    /// '+'
    plus = 0x0000002b,
    /// ','
    comma = 0x0000002c,
    /// '-'
    minus = 0x0000002d,
    /// '.'
    period = 0x0000002e,
    /// '/'
    slash = 0x0000002f,
    /// '0'
    num_0 = 0x00000030,
    /// '1'
    num_1 = 0x00000031,
    /// '2'
    num_2 = 0x00000032,
    /// '3'
    num_3 = 0x00000033,
    /// '4'
    num_4 = 0x00000034,
    /// '5'
    num_5 = 0x00000035,
    /// '6'
    num_6 = 0x00000036,
    /// '7'
    num_7 = 0x00000037,
    /// '8'
    num_8 = 0x00000038,
    /// '9'
    num_9 = 0x00000039,
    /// ':'
    colon = 0x0000003a,
    /// ';'
    semicolon = 0x0000003b,
    /// '<'
    less = 0x0000003c,
    /// '='
    equals = 0x0000003d,
    /// '>'
    greater = 0x0000003e,
    /// '?'
    question = 0x0000003f,
    /// '@'
    at = 0x00000040,
    /// '['
    leftbracket = 0x0000005b,
    /// '\\'
    backslash = 0x0000005c,
    /// ']'
    rightbracket = 0x0000005d,
    /// '^'
    caret = 0x0000005e,
    /// '_'
    underscore = 0x0000005f,
    /// '`'
    grave = 0x00000060,
    /// 'a'
    a = 0x00000061,
    /// 'b'
    b = 0x00000062,
    /// 'c'
    c = 0x00000063,
    /// 'd'
    d = 0x00000064,
    /// 'e'
    e = 0x00000065,
    /// 'f'
    f = 0x00000066,
    /// 'g'
    g = 0x00000067,
    /// 'h'
    h = 0x00000068,
    /// 'i'
    i = 0x00000069,
    /// 'j'
    j = 0x0000006a,
    /// 'k'
    k = 0x0000006b,
    /// 'l'
    l = 0x0000006c,
    /// 'm'
    m = 0x0000006d,
    /// 'n'
    n = 0x0000006e,
    /// 'o'
    o = 0x0000006f,
    /// 'p'
    p = 0x00000070,
    /// 'q'
    q = 0x00000071,
    /// 'r'
    r = 0x00000072,
    /// 's'
    s = 0x00000073,
    /// 't'
    t = 0x00000074,
    /// 'u'
    u = 0x00000075,
    /// 'v'
    v = 0x00000076,
    /// 'w'
    w = 0x00000077,
    /// 'x'
    x = 0x00000078,
    /// 'y'
    y = 0x00000079,
    /// 'z'
    z = 0x0000007a,
    /// '{'
    leftbrace = 0x0000007b,
    /// '|'
    pipe = 0x0000007c,
    /// '}'
    rightbrace = 0x0000007d,
    /// '~'
    tilde = 0x0000007e,
    /// '\x7F'
    delete = 0x0000007f,
    /// '\xB1'
    plusminus = 0x000000b1,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CAPSLOCK)
    capslock = 0x40000039,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F1)
    f1 = 0x4000003a,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F2)
    f2 = 0x4000003b,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F3)
    f3 = 0x4000003c,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F4)
    f4 = 0x4000003d,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F5)
    f5 = 0x4000003e,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F6)
    f6 = 0x4000003f,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F7)
    f7 = 0x40000040,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F8)
    f8 = 0x40000041,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F9)
    f9 = 0x40000042,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F10)
    f10 = 0x40000043,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F11)
    f11 = 0x40000044,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F12)
    f12 = 0x40000045,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN)
    printscreen = 0x40000046,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SCROLLLOCK)
    scrolllock = 0x40000047,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAUSE)
    pause = 0x40000048,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_INSERT)
    insert = 0x40000049,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HOME)
    home = 0x4000004a,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEUP)
    pageup = 0x4000004b,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_END)
    end = 0x4000004d,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEDOWN)
    pagedown = 0x4000004e,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RIGHT)
    right = 0x4000004f,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LEFT)
    left = 0x40000050,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DOWN)
    down = 0x40000051,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UP)
    up = 0x40000052,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR)
    numlockclear = 0x40000053,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE)
    kp_divide = 0x40000054,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY)
    kp_multiply = 0x40000055,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS)
    kp_minus = 0x40000056,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS)
    kp_plus = 0x40000057,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_ENTER)
    kp_enter = 0x40000058,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_1)
    kp_1 = 0x40000059,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_2)
    kp_2 = 0x4000005a,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_3)
    kp_3 = 0x4000005b,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_4)
    kp_4 = 0x4000005c,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_5)
    kp_5 = 0x4000005d,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_6)
    kp_6 = 0x4000005e,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_7)
    kp_7 = 0x4000005f,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_8)
    kp_8 = 0x40000060,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_9)
    kp_9 = 0x40000061,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_0)
    kp_0 = 0x40000062,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD)
    kp_period = 0x40000063,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APPLICATION)
    application = 0x40000065,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_POWER)
    power = 0x40000066,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALS)
    kp_equals = 0x40000067,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F13)
    f13 = 0x40000068,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F14)
    f14 = 0x40000069,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F15)
    f15 = 0x4000006a,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F16)
    f16 = 0x4000006b,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F17)
    f17 = 0x4000006c,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F18)
    f18 = 0x4000006d,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F19)
    f19 = 0x4000006e,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F20)
    f20 = 0x4000006f,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F21)
    f21 = 0x40000070,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F22)
    f22 = 0x40000071,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F23)
    f23 = 0x40000072,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F24)
    f24 = 0x40000073,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXECUTE)
    execute = 0x40000074,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HELP)
    help = 0x40000075,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MENU)
    menu = 0x40000076,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SELECT)
    select = 0x40000077,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_STOP)
    stop = 0x40000078,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AGAIN)
    again = 0x40000079,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UNDO)
    undo = 0x4000007a,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CUT)
    cut = 0x4000007b,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COPY)
    copy = 0x4000007c,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PASTE)
    paste = 0x4000007d,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_FIND)
    find = 0x4000007e,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MUTE)
    mute = 0x4000007f,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEUP)
    volumeup = 0x40000080,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEDOWN)
    volumedown = 0x40000081,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COMMA)
    kp_comma = 0x40000085,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400)
    kp_equalsas400 = 0x40000086,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ALTERASE)
    alterase = 0x40000099,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SYSREQ)
    sysreq = 0x4000009a,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CANCEL)
    cancel = 0x4000009b,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEAR)
    clear = 0x4000009c,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRIOR)
    prior = 0x4000009d,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RETURN2)
    return2 = 0x4000009e,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SEPARATOR)
    separator = 0x4000009f,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OUT)
    out = 0x400000a0,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OPER)
    oper = 0x400000a1,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEARAGAIN)
    clearagain = 0x400000a2,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CRSEL)
    crsel = 0x400000a3,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXSEL)
    exsel = 0x400000a4,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_00)
    kp_00 = 0x400000b0,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_000)
    kp_000 = 0x400000b1,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR)
    thousandsseparator = 0x400000b2,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR)
    decimalseparator = 0x400000b3,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYUNIT)
    currencyunit = 0x400000b4,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYSUBUNIT)
    currencysubunit = 0x400000b5,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN)
    kp_leftparen = 0x400000b6,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN)
    kp_rightparen = 0x400000b7,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE)
    kp_leftbrace = 0x400000b8,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE)
    kp_rightbrace = 0x400000b9,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_TAB)
    kp_tab = 0x400000ba,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BACKSPACE)
    kp_backspace = 0x400000bb,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_A)
    kp_a = 0x400000bc,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_B)
    kp_b = 0x400000bd,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_C)
    kp_c = 0x400000be,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_D)
    kp_d = 0x400000bf,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_E)
    kp_e = 0x400000c0,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_F)
    kp_f = 0x400000c1,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_XOR)
    kp_xor = 0x400000c2,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_POWER)
    kp_power = 0x400000c3,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERCENT)
    kp_percent = 0x400000c4,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LESS)
    kp_less = 0x400000c5,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_GREATER)
    kp_greater = 0x400000c6,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AMPERSAND)
    kp_ampersand = 0x400000c7,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLAMPERSAND)
    kp_dblampersand = 0x400000c8,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR)
    kp_verticalbar = 0x400000c9,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLVERTICALBAR)
    kp_dblverticalbar = 0x400000ca,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COLON)
    kp_colon = 0x400000cb,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HASH)
    kp_hash = 0x400000cc,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_SPACE)
    kp_space = 0x400000cd,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AT)
    kp_at = 0x400000ce,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EXCLAM)
    kp_exclam = 0x400000cf,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSTORE)
    kp_memstore = 0x400000d0,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMRECALL)
    kp_memrecall = 0x400000d1,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR)
    kp_memclear = 0x400000d2,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMADD)
    kp_memadd = 0x400000d3,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT)
    kp_memsubtract = 0x400000d4,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY)
    kp_memmultiply = 0x400000d5,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE)
    kp_memdivide = 0x400000d6,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS)
    kp_plusminus = 0x400000d7,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEAR)
    kp_clear = 0x400000d8,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY)
    kp_clearentry = 0x400000d9,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BINARY)
    kp_binary = 0x400000da,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_OCTAL)
    kp_octal = 0x400000db,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DECIMAL)
    kp_decimal = 0x400000dc,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL)
    kp_hexadecimal = 0x400000dd,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LCTRL)
    lctrl = 0x400000e0,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LSHIFT)
    lshift = 0x400000e1,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LALT)
    lalt = 0x400000e2,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LGUI)
    lgui = 0x400000e3,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RCTRL)
    rctrl = 0x400000e4,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RSHIFT)
    rshift = 0x400000e5,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RALT)
    ralt = 0x400000e6,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RGUI)
    rgui = 0x400000e7,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MODE)
    mode = 0x40000101,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SLEEP)
    sleep = 0x40000102,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_WAKE)
    wake = 0x40000103,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_INCREMENT)
    channel_increment = 0x40000104,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_DECREMENT)
    channel_decrement = 0x40000105,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY)
    media_play = 0x40000106,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PAUSE)
    media_pause = 0x40000107,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_RECORD)
    media_record = 0x40000108,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_FAST_FORWARD)
    media_fast_forward = 0x40000109,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_REWIND)
    media_rewind = 0x4000010a,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_NEXT_TRACK)
    media_next_track = 0x4000010b,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PREVIOUS_TRACK)
    media_previous_track = 0x4000010c,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_STOP)
    media_stop = 0x4000010d,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_EJECT)
    media_eject = 0x4000010e,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY_PAUSE)
    media_play_pause = 0x4000010f,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_SELECT)
    media_select = 0x40000110,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_NEW)
    ac_new = 0x40000111,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_OPEN)
    ac_open = 0x40000112,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_CLOSE)
    ac_close = 0x40000113,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_EXIT)
    ac_exit = 0x40000114,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SAVE)
    ac_save = 0x40000115,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PRINT)
    ac_print = 0x40000116,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PROPERTIES)
    ac_properties = 0x40000117,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH)
    ac_search = 0x40000118,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME)
    ac_home = 0x40000119,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK)
    ac_back = 0x4000011a,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD)
    ac_forward = 0x4000011b,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP)
    ac_stop = 0x4000011c,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH)
    ac_refresh = 0x4000011d,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS)
    ac_bookmarks = 0x4000011e,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTLEFT)
    softleft = 0x4000011f,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTRIGHT)
    softright = 0x40000120,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CALL)
    call = 0x40000121,
    /// SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ENDCALL)
    endcall = 0x40000122,
    /// Extended key Left Tab
    left_tab = 0x20000001,
    /// Extended key Level 5 Shift
    level5_shift = 0x20000002,
    /// Extended key Multi-key Compose
    multi_key_compose = 0x20000003,
    /// Extended key Left Meta
    lmeta = 0x20000004,
    /// Extended key Right Meta
    rmeta = 0x20000005,
    /// Extended key Left Hyper
    lhyper = 0x20000006,
    /// Extended key Right Hyper
    rhyper = 0x20000007,
};

pub inline fn SDL_SCANCODE_TO_KEYCODE(sc: scancode.SDL_Scancode) SDL_Keycode {
    return sc | SDL_Keycode.scancode_mask;
}

///
/// Valid key modifiers (possibly OR'd together).
///
/// \since This datatype is available since SDL 3.2.0.
///
pub const SDL_Keymod = enum(u16) {
    /// no modifier is applicable.
    none = 0x0000,
    /// the left Shift key is down.
    lshift = 0x0001,
    /// the right Shift key is down.
    rshift = 0x0002,
    /// the Level 5 Shift key is down.
    level5 = 0x0004,
    /// the left Ctrl (Control) key is down.
    lctrl = 0x0040,
    /// the right Ctrl (Control) key is down.
    rctrl = 0x0080,
    /// the left Alt key is down.
    lalt = 0x0100,
    /// the right Alt key is down.
    ralt = 0x0200,
    /// the left GUI key (often the Windows key) is down.
    lgui = 0x0400,
    /// the right GUI key (often the Windows key) is down.
    rgui = 0x0800,
    /// the Num Lock key (may be located on an extended keypad) is down.
    num = 0x1000,
    /// the Caps Lock key is down.
    caps = 0x2000,
    /// the !AltGr key is down.
    mode = 0x4000,
    /// the Scroll Lock key is down.
    scroll = 0x8000,
    /// Any Ctrl key is down.
    ctrl = (SDL_Keymod.lctrl | SDL_Keymod.rctrl),
    /// Any Shift key is down.
    shift = (SDL_Keymod.lshift | SDL_Keymod.rshift),
    /// Any Alt key is down.
    alt = (SDL_Keymod.lalt | SDL_Keymod.ralt),
    /// Any GUI key is down.
    gui = (SDL_Keymod.lgui | SDL_Keymod.rgui),
};
